TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += tjmper.db
DB += tjmper_error_setter.db
DATA += tjmper.proto

#=======================================
include $(TOP)/configure/RULES
